
version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mcq_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  app:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_DATABASE: mcq_db
      DB_USER: user
      DB_PASSWORD: password
      OPENAI_API_KEY: your_openai_api_key_here
    ports:
      - "5000:5000"
    